//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uixe.Watcher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmLogin_Location {
            get {
                return ((global::System.Drawing.Point)(this["frmLogin_Location"]));
            }
            set {
                this["frmLogin_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("030800")]
        public string frmLogin_txtUser {
            get {
                return ((string)(this["frmLogin_txtUser"]));
            }
            set {
                this["frmLogin_txtUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LastLaneView {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LastLaneView"]));
            }
            set {
                this["LastLaneView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("166")]
        public int scMain_SplitterDistance {
            get {
                return ((int)(this["scMain_SplitterDistance"]));
            }
            set {
                this["scMain_SplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool lanenoisselectall {
            get {
                return ((bool)(this["lanenoisselectall"]));
            }
            set {
                this["lanenoisselectall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool paramsisselectall {
            get {
                return ((bool)(this["paramsisselectall"]));
            }
            set {
                this["paramsisselectall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool buildparamsisselectall {
            get {
                return ((bool)(this["buildparamsisselectall"]));
            }
            set {
                this["buildparamsisselectall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool frmparamsend_aototink {
            get {
                return ((bool)(this["frmparamsend_aototink"]));
            }
            set {
                this["frmparamsend_aototink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Office 2016 Colorful")]
        public string SkinStyle {
            get {
                return ((string)(this["SkinStyle"]));
            }
            set {
                this["SkinStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("321")]
        public int tcovierwer_split {
            get {
                return ((int)(this["tcovierwer_split"]));
            }
            set {
                this["tcovierwer_split"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("facebook提示音")]
        public string Ring {
            get {
                return ((string)(this["Ring"]));
            }
            set {
                this["Ring"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpeechLvSeTongDao {
            get {
                return ((bool)(this["SpeechLvSeTongDao"]));
            }
            set {
                this["SpeechLvSeTongDao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpeedBlackListPlate {
            get {
                return ((bool)(this["SpeedBlackListPlate"]));
            }
            set {
                this["SpeedBlackListPlate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tco_chexingbufu {
            get {
                return ((bool)(this["tco_chexingbufu"]));
            }
            set {
                this["tco_chexingbufu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tco_chepaibufu {
            get {
                return ((bool)(this["tco_chepaibufu"]));
            }
            set {
                this["tco_chepaibufu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool tco_chaoshichaosu {
            get {
                return ((bool)(this["tco_chaoshichaosu"]));
            }
            set {
                this["tco_chaoshichaosu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string plazaid {
            get {
                return ((string)(this["plazaid"]));
            }
            set {
                this["plazaid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8880")]
        public int KeyboardPort {
            get {
                return ((int)(this["KeyboardPort"]));
            }
            set {
                this["KeyboardPort"] = value;
            }
        }
    }
}
